// SPDX-License-Identifier: GPL-2.0
/*
 * Qualcomm XPCS platform device driver.
 *
 * Thin platform_device wrapper for the DW XPCS on SA8797P (Nord).
 * Bridges the memory-mapped APB register space to the upstream
 * pcs-xpcs.c core via a custom regmap and devm_xpcs_regmap_register().
 *
 * The Qualcomm XPCS APB register space is segmented (IPCAT nordschleife_2.0):
 *
 *   0x0000–0x1FFF  SR_XS_PCS standard registers  (MDIO_MMD_PCS,   reg < 0x8000)
 *   0x2000–0x3FFF  VR_XS_PCS vendor registers     (MDIO_MMD_PCS,   reg >= 0x8000)
 *   0x4000–0x4FFF  SR_MII   standard registers    (MDIO_MMD_VEND2, reg < 0x8000)
 *   0x5000–0x5100  VR_MII   vendor registers      (MDIO_MMD_VEND2, reg >= 0x8000)
 *
 * The custom regmap translates (dev << 16) | reg addresses (as produced by
 * pcs-xpcs-regmap.c) to the correct APB byte offsets.
 *
 * Copyright (C) 2024 Qualcomm Technologies, Inc.
 */

#include <linux/clk.h>
#include <linux/mii.h>
#include <linux/module.h>
#include <linux/of.h>
#include <linux/platform_device.h>
#include <linux/pm_runtime.h>
#include <linux/regmap.h>
#include <linux/pcs/pcs-xpcs-regmap.h>

#include "pcs-xpcs.h"

/*
 * Translate a (dev << 16) | reg MDIO C45 address to an APB byte offset.
 * Verified against IPCAT nordschleife_2.0, module DWC_PORT1_DWC_XPCS.
 */
static ptrdiff_t qcom_xpcs_addr_to_offset(unsigned int addr)
{
	bool vendor = (addr & 0x8000);
	int dev = (addr >> 16) & 0x1f;
	int reg = addr & 0xffff;

	switch (dev) {
	case MDIO_MMD_PCS:
		/* PCS std: byte = reg << 2; PCS vnd: byte = (reg - 0x7800) << 2 */
		if (vendor)
			return (ptrdiff_t)(reg - 0x7800) << 2;
		return (ptrdiff_t)reg << 2;

	case MDIO_MMD_VEND2:
		/* VEND2 std: byte = (reg << 2) + 0x4000 */
		/* VEND2 vnd: byte = ((reg - 0x8000) << 2) + 0x5000 */
		if (vendor)
			return (ptrdiff_t)((reg - 0x8000) << 2) + 0x5000;
		return (ptrdiff_t)(reg << 2) + 0x4000;

	default:
		return -1;
	}
}

static int qcom_xpcs_reg_read(void *context, unsigned int addr, unsigned int *val)
{
	void __iomem *base = context;
	int dev = (addr >> 16) & 0x1f;
	int reg = addr & 0xffff;
	ptrdiff_t off;

	/*
	 * Return QCOM_NORD_XPCS_ID via MII_PHYSID1/2 so xpcs_identify()
	 * selects qcom_nord_xpcs_compat instead of synopsys_xpcs_compat.
	 * Precedent: sja1105_mdio.c lines 23-26.
	 */
	if (dev == MDIO_MMD_PCS && reg == MII_PHYSID1) {
		*val = QCOM_NORD_XPCS_ID >> 16;
		return 0;
	}
	if (dev == MDIO_MMD_PCS && reg == MII_PHYSID2) {
		*val = QCOM_NORD_XPCS_ID & 0xffff;
		return 0;
	}

	off = qcom_xpcs_addr_to_offset(addr);
	if (off < 0) {
		/* Unhandled MMD (e.g. MDIO_MMD_PMAPMD): return 0xffff like
		 * MDIO does for non-existent registers. Precedent: sja1105_mdio.c:21.
		 */
		*val = 0xffff;
		return 0;
	}

	*val = readl(base + off) & 0xffff;
	return 0;
}

static int qcom_xpcs_reg_write(void *context, unsigned int addr, unsigned int val)
{
	void __iomem *base = context;
	ptrdiff_t off = qcom_xpcs_addr_to_offset(addr);

	if (off < 0)
		return -EINVAL;

	writel(val & 0xffff, base + off);
	return 0;
}

static const struct regmap_config qcom_xpcs_regmap_config = {
	.reg_bits	= 32,
	.val_bits	= 32,
	.reg_read	= qcom_xpcs_reg_read,
	.reg_write	= qcom_xpcs_reg_write,
};

static int qcom_xpcs_probe(struct platform_device *pdev)
{
	struct device *dev = &pdev->dev;
	const struct xpcs_regmap_config cfg = { .reg_indir = false };
	struct xpcs_regmap_config xcfg = cfg;
	void __iomem *base;
	struct regmap *regmap;
	struct dw_xpcs *xpcs;

	dev_info(dev, "probing QCOM XPCS\n");

	base = devm_platform_ioremap_resource(pdev, 0);
	if (IS_ERR(base))
		return PTR_ERR(base);

	dev_info(dev, "XPCS APB mapped at %px\n", base);

	/*
	 * Create a custom regmap that translates (dev << 16) | reg addresses
	 * (as generated by pcs-xpcs-regmap.c) to Qualcomm APB byte offsets.
	 */
	regmap = devm_regmap_init(dev, NULL, base, &qcom_xpcs_regmap_config);
	if (IS_ERR(regmap))
		return PTR_ERR(regmap);

	xcfg.regmap = regmap;
	xpcs = devm_xpcs_regmap_register(dev, &xcfg);
	if (IS_ERR(xpcs))
		return dev_err_probe(dev, PTR_ERR(xpcs), "failed to register XPCS\n");

	dev_info(dev, "XPCS registered, id=0x%08x\n", xpcs->mdiodev->addr);

	/*
	 * Enable RPCS and XGXS clocks listed in the DT node.  Use
	 * devm_clk_bulk_get_all() so this is a no-op on boards that omit them.
	 */
	{
		struct clk_bulk_data *clks;
		int n = devm_clk_bulk_get_all(dev, &clks);

		if (n < 0)
			return dev_err_probe(dev, n, "failed to get clocks\n");
		dev_info(dev, "enabling %d XPCS clocks\n", n);
		if (n > 0) {
			int ret = clk_bulk_prepare_enable(n, clks);

			if (ret)
				return dev_err_probe(dev, ret, "failed to enable clocks\n");
		}
	}

	platform_set_drvdata(pdev, xpcs);

	pm_runtime_enable(dev);

	dev_info(dev, "QCOM XPCS probe complete\n");
	return 0;
}

static void qcom_xpcs_remove(struct platform_device *pdev)
{
	pm_runtime_disable(&pdev->dev);
}

static const struct of_device_id qcom_xpcs_of_ids[] = {
	{ .compatible = "qcom,xpcs" },
	{ }
};
MODULE_DEVICE_TABLE(of, qcom_xpcs_of_ids);

static struct platform_driver qcom_xpcs_driver = {
	.probe	= qcom_xpcs_probe,
	.remove	= qcom_xpcs_remove,
	.driver	= {
		.name		= "qcom-xpcs",
		.of_match_table	= qcom_xpcs_of_ids,
	},
};
module_platform_driver(qcom_xpcs_driver);

MODULE_DESCRIPTION("Qualcomm DW XPCS platform driver");
MODULE_LICENSE("GPL");
